#!/bin/bash

range[1]=$((RANDOM%15+1))
range[2]=$((RANDOM%15+1))
range[3]=$((RANDOM%15+1))
range[4]=$((RANDOM%15+1))
range[5]=$((RANDOM%15+1))
i=0
echo "These are your numbers:"
while [ 1 ]
do

	if [ $i -lt 5 ]
	then
		i=$[$i+1]
		echo ${range[i]}
	else
		exit
	fi

done
